env:
  main_path: "~/Desktop/AerialRobotics/apairaikar_p3a/maps"
  map_file: "example.txt"

textures:
  main_path: "~/Desktop/AerialRobotics/apairaikar_p3a/textures"
  pic: "Window.png"
  pptx: "Windows.pptx"

blender_location:
  main_path: "~/Desktop/AerialRobotics/apairaikar_p3a/"
  file_name: "main.blend"    



